In [8]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
type(a)

numpy.ndarray

In [10]:
b = [1,2,3,4,5]

In [11]:
b+6

TypeError: can only concatenate list (not "int") to list

In [12]:
b+a

array([ 2,  4,  6,  8, 10])

In [13]:
b+[6]

[1, 2, 3, 4, 5, 6]

In [14]:
a+[6]

array([ 7,  8,  9, 10, 11])

In [16]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
d = [[1,2,3],[4,5,6],[7,8,9]]
d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
e*c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [19]:
e**c

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [20]:
e//c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
e=e//c

In [22]:
e

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
e=e+c

In [25]:
e

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [27]:
e=np.dot(e,c)
e

array([[ 666,  819,  972],
       [1260, 1548, 1836],
       [1854, 2277, 2700]])

In [28]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
e

array([[ 666,  819,  972],
       [1260, 1548, 1836],
       [1854, 2277, 2700]])

In [30]:
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.array([[1,1,1],[1,1,1],[1,1,1]])